<?xml version="1.0"?>
<package format="2">
  <name>morai</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>

  <maintainer email="bong7121@koreatech.ac.kr">kroad</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>catkin</buildtool_depend>

  <!-- build 시 메시지 생성 -->
  <build_depend>message_generation</build_depend>   <!-- ★ 추가 -->

  <!-- 런타임 메시지 -->
  <exec_depend>message_runtime</exec_depend>        <!-- ★ 추가 -->

  <!-- 기존 의존성 -->
  <build_depend>std_msgs</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>geometry_msgs</build_depend>

  <exec_depend>rospy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>python3-pyproj</exec_depend>

  <export/>
</package>
