<?xml version="1.0"?>
<package format="2">
  <name>planning_pkg_2025</name>
  <version>0.0.1</version>
  <description>ROS1-converted planning package.</description>
  <maintainer email="ulix7990@gmail.com">ulix7990</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>roscpp</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>geometry_msgs</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>roslib</build_depend>
  <build_depend>eigen</build_depend>
  <build_depend>libcgal-dev</build_depend>
  <build_depend>nlohmann-json3-dev</build_depend>

  <exec_depend>roscpp</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>roslib</exec_depend>
  <exec_depend>eigen</exec_depend>
  <exec_depend>libcgal-dev</exec_depend>
  <exec_depend>nlohmann-json3-dev</exec_depend>

  <export>
  </export>
</package>
